// Vendors the handful of brand paths the app draws, from simple-icons, into
// src/lib/brand-paths.ts. Run when a tool is added to onboarding-tools.ts:
//   node scripts/brand-marks.mjs
// simple-icons is a devDependency only; the app ships six paths, not 3,000.
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";

const WANT = ["quickbooks", "sage", "hubspot", "googlesheets", "dropbox", "zapier"];
const byslug = new Map(
  Object.values(si)
    .filter((x) => x && x.slug)
    .map((x) => [x.slug, x]),
);
const lines = WANT.map((slug) => {
  const i = byslug.get(slug);
  if (!i) throw new Error(`simple-icons has no ${slug}`);
  return `  ${slug}: { title: ${JSON.stringify(i.title)}, hex: "#${i.hex}", path: ${JSON.stringify(i.path)} },`;
});
writeFileSync(
  "src/lib/brand-paths.ts",
  `// Generated by scripts/brand-marks.mjs from simple-icons (CC0). Do not edit.
export type BrandPath = { title: string; hex: string; path: string };
export const BRAND_PATHS: Record<string, BrandPath> = {
${lines.join("\n")}
};
`,
);
console.log(`wrote ${WANT.length} brand paths`);
