/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TechnicalSolutionsRouteImport } from './routes/technical-solutions'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as OwnersOwnerRouteImport } from './routes/owners.$owner'
import { Route as TechnicalSolutionsIndexRouteImport } from './routes/technical-solutions.index'
import { Route as TechnicalSolutionsIdRouteImport } from './routes/technical-solutions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalSolutionsRoute = TechnicalSolutionsRouteImport.update({
  id: '/technical-solutions',
  path: '/technical-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const OwnersOwnerRoute = OwnersOwnerRouteImport.update({
  id: '/owners/$owner',
  path: '/owners/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalSolutionsIndexRoute = TechnicalSolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicalSolutionsRoute,
} as any)
const TechnicalSolutionsIdRoute = TechnicalSolutionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TechnicalSolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/technical-solutions': typeof TechnicalSolutionsRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/owners/$owner': typeof OwnersOwnerRoute
  '/technical-solutions/$id': typeof TechnicalSolutionsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/technical-solutions/': typeof TechnicalSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/owners/$owner': typeof OwnersOwnerRoute
  '/technical-solutions/$id': typeof TechnicalSolutionsIdRoute
  '/customers': typeof CustomersIndexRoute
  '/technical-solutions': typeof TechnicalSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/technical-solutions': typeof TechnicalSolutionsRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/owners/$owner': typeof OwnersOwnerRoute
  '/technical-solutions/$id': typeof TechnicalSolutionsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/technical-solutions/': typeof TechnicalSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/portfolio'
    | '/settings'
    | '/technical-solutions'
    | '/customers/$customerId'
    | '/owners/$owner'
    | '/technical-solutions/$id'
    | '/customers/'
    | '/technical-solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfolio'
    | '/settings'
    | '/customers/$customerId'
    | '/owners/$owner'
    | '/technical-solutions/$id'
    | '/customers'
    | '/technical-solutions'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/portfolio'
    | '/settings'
    | '/technical-solutions'
    | '/customers/$customerId'
    | '/owners/$owner'
    | '/technical-solutions/$id'
    | '/customers/'
    | '/technical-solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalSolutionsRoute: typeof TechnicalSolutionsRouteWithChildren
  OwnersOwnerRoute: typeof OwnersOwnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-solutions': {
      id: '/technical-solutions'
      path: '/technical-solutions'
      fullPath: '/technical-solutions'
      preLoaderRoute: typeof TechnicalSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/owners/$owner': {
      id: '/owners/$owner'
      path: '/owners/$owner'
      fullPath: '/owners/$owner'
      preLoaderRoute: typeof OwnersOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-solutions/': {
      id: '/technical-solutions/'
      path: '/'
      fullPath: '/technical-solutions/'
      preLoaderRoute: typeof TechnicalSolutionsIndexRouteImport
      parentRoute: typeof TechnicalSolutionsRoute
    }
    '/technical-solutions/$id': {
      id: '/technical-solutions/$id'
      path: '/$id'
      fullPath: '/technical-solutions/$id'
      preLoaderRoute: typeof TechnicalSolutionsIdRouteImport
      parentRoute: typeof TechnicalSolutionsRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface TechnicalSolutionsRouteChildren {
  TechnicalSolutionsIdRoute: typeof TechnicalSolutionsIdRoute
  TechnicalSolutionsIndexRoute: typeof TechnicalSolutionsIndexRoute
}

const TechnicalSolutionsRouteChildren: TechnicalSolutionsRouteChildren = {
  TechnicalSolutionsIdRoute: TechnicalSolutionsIdRoute,
  TechnicalSolutionsIndexRoute: TechnicalSolutionsIndexRoute,
}

const TechnicalSolutionsRouteWithChildren =
  TechnicalSolutionsRoute._addFileChildren(TechnicalSolutionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  TechnicalSolutionsRoute: TechnicalSolutionsRouteWithChildren,
  OwnersOwnerRoute: OwnersOwnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
