-- 0022 — Weekly plan snapshots and their share links.
--
-- Design: docs/design/portal-access.md §2.5, renumbered 0014 -> 0022 per the
-- ledger in docs/PLAN.md.
--
-- NAMING-COLLISION CHECK: `plan_snapshots` checked against the full 28-table
-- prototype list in the 0003 header. No collision. Recorded near-miss, because
-- a future rename must re-check it: the prototype owns `proposal_snapshots`.
-- Distinct.
--
-- WHAT `content` IS. A frozen SharedPlanSnapshot: the output of
-- buildSharedPlanDTO — the same single serializer the /plan page, the /portal
-- page and the internal preview render through — plus a delta section. There is
-- no second serializer, which is why full-row customer reads of this table are
-- safe by construction: the column already holds the customer-safe projection
-- and nothing else. src/lib/__tests__/external-portal-auth.test.ts asserts the
-- key set against the same frozen allowlist for every consumer, snapshot
-- included.
--
-- CORRECTIONS ARE APPENDED, NEVER EDITED. A snapshot is what we told the
-- customer on a given week. Fixing it inserts a new row with supersedes_id
-- pointing at the old one; the old row stays byte-identical. There is
-- deliberately no update or delete policy for any role.
--
-- Rollback: supabase/down/0022_down.sql (archives to v2_archive).

create table plan_snapshots (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null default '00000000-0000-4000-8000-000000000001' references orgs (id),
  implementation_id uuid not null references implementations (id) on delete cascade,
  week_start date not null,
  generated_at timestamptz not null default now(),
  -- null = generated by the cron, which is a fact about the row, not a missing
  -- value.
  generated_by uuid references portal_profiles (id) on delete set null,
  supersedes_id uuid references plan_snapshots (id) on delete set null,
  content jsonb not null,
  -- Minted lazily, only when someone shares this snapshot. sha256 hex of
  -- 'gcps_' + 32 random bytes; the raw token is never stored.
  share_token_hash text unique,
  share_expires_at timestamptz,
  share_revoked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (implementation_id, week_start, generated_at),
  -- A share token cannot exist without an expiry. The brief requires external
  -- access to be expiring and revocable, and "we forgot to set an expiry" is
  -- exactly how a permanent public link gets created — so it is refused by the
  -- database rather than by a code path someone can forget to call.
  constraint plan_snapshots_share_expiry_check
    check (share_token_hash is null or share_expires_at is not null)
);

create index plan_snapshots_impl_week_idx
  on plan_snapshots (implementation_id, week_start desc, generated_at desc);
create index plan_snapshots_share_idx
  on plan_snapshots (share_token_hash)
  where share_token_hash is not null;

alter table plan_snapshots enable row level security;

-- Internal read. Writes — including the cron's — run on the service role, so
-- there is deliberately no insert policy for a browser session either: a
-- snapshot is generated, never typed.
create policy "plan_snapshots internal select" on plan_snapshots
  for select to authenticated using (portal_is_internal());

-- Customer-auth read, honouring the implementation scope from 0011. Full-row is
-- safe here for the reason in the header: every column is either the frozen
-- customer-safe DTO or metadata about it.
create policy "plan_snapshots customer select" on plan_snapshots
  for select to authenticated
  using (
    exists (
      select 1
        from implementations i
        join customer_users cu on cu.customer_id = i.customer_id
       where i.id = plan_snapshots.implementation_id
         and cu.profile_id = auth.uid()
         and (cu.implementation_id is null or cu.implementation_id = i.id)
    )
  );

-- No anon policy, on purpose: the snapshot share link is verified by the server
-- function that hashes the token, never by RLS (a link bearer has no
-- auth.uid()).
